import * as THREE from 'three';

const WORLD=180, HALF=WORLD/2, SAVE_KEY='deadline-wasteland-v1';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x80909a);scene.fog=new THREE.Fog(0x80909a,55,170);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,500);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;scene.add(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xb8c9d2,0x302b20,1.25);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe1ae,2);sun.position.set(40,80,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.9});const mats={ground:mat(0x5b6049),road:mat(0x303432),wood:mat(0x624a31),leaf:mat(0x394a35),rock:mat(0x64615a),metal:mat(0x566066),zombie:mat(0x52695b),player:mat(0xb9b6a1),car:mat(0x38484c),building:mat(0x494641)};
const ground=new THREE.Mesh(new THREE.PlaneGeometry(WORLD,WORLD),mats.ground);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const road=new THREE.Mesh(new THREE.PlaneGeometry(16,WORLD),mats.road);road.rotation.x=-Math.PI/2;road.position.y=.012;scene.add(road);const road2=road.clone();road2.geometry=new THREE.PlaneGeometry(WORLD,12);road2.position.set(0,.014,0);scene.add(road2);
const player=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1,4,8),mats.player);body.position.y=1;body.castShadow=true;player.add(body);player.position.set(0,0,18);scene.add(player);
const state={hp:100,hunger:100,thirst:100,stamina:100,wood:0,scrap:0,stone:0,food:2,water:2,day:1,time:6,firstPerson:true,driving:false,carHealth:100,fuel:72,noise:0,dead:false};
let yaw=0,pitch=-.15,velocity=new THREE.Vector3(),keys={},resources=[],zombies=[],buildings=[],car=null,buildMode=false,joystick={x:0,y:0},look={active:false};

function box(x,y,z,sx,sy,sz,m){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
function tree(x,z){const g=new THREE.Group();g.position.set(x,0,z);const t=new THREE.Mesh(new THREE.CylinderGeometry(.22,.35,2.2,6),mats.wood);t.position.y=1.1;const l=new THREE.Mesh(new THREE.ConeGeometry(1.3,3.4,7),mats.leaf);l.position.y=3.1;t.castShadow=l.castShadow=true;g.add(t,l);scene.add(g);return g}
function rock(x,z){const o=new THREE.Mesh(new THREE.DodecahedronGeometry(.8+Math.random()*0.7,0),mats.rock);o.position.set(x,.5,z);o.scale.y=.65;o.castShadow=true;scene.add(o);resources.push({obj:o,type:'stone',amount:1+Math.floor(Math.random()*3),respawn:0})}
function scrapPile(x,z){const o=box(x,.35,z,1.2,.65,1,mats.metal);o.rotation.y=Math.random()*3;resources.push({obj:o,type:'scrap',amount:1+Math.floor(Math.random()*2),respawn:0})}
function treeResource(x,z){const g=tree(x,z);resources.push({obj:g,type:'wood',amount:2,respawn:0})}
function shack(x,z){const g=new THREE.Group();g.position.set(x,0,z);const b=new THREE.Mesh(new THREE.BoxGeometry(8,4,7),mats.building);b.position.y=2;b.castShadow=true;g.add(b);const roof=new THREE.Mesh(new THREE.BoxGeometry(8.5,.5,7.5),mats.wood);roof.position.y=4.25;roof.castShadow=true;g.add(roof);scene.add(g);buildings.push(g)}
for(let i=0;i<24;i++){let x=(Math.random()-.5)*150,z=(Math.random()-.5)*150;if(Math.abs(x)<12||Math.abs(z)<12){i--;continue}treeResource(x,z)}
for(let i=0;i<22;i++){let x=(Math.random()-.5)*150,z=(Math.random()-.5)*150;if(Math.abs(x)<10&&Math.abs(z)<10){i--;continue}rock(x,z)}
for(let i=0;i<12;i++){let x=(Math.random()-.5)*150,z=(Math.random()-.5)*150;if(Math.abs(x)<18&&Math.abs(z)<18){i--;continue}scrapPile(x,z)}
shack(-30,-28);shack(34,-20);shack(-34,35);
car=new THREE.Group();car.position.set(7,0,15);const cb=box(0,1.05,0,3.2,.9,5,mats.car);car.add(cb);const roof=box(0,1.8,-.1,2.6,.7,2.7,mats.car);car.add(roof);for(const sx of [-1,1])for(const sz of [-1,1]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,.35,10),mat(0x181a1a));w.rotation.z=Math.PI/2;w.position.set(sx*1.45,.55,sz*1.75);car.add(w)}scene.add(car);
function spawnZombie(x,z){const g=new THREE.Group();const m=new THREE.Mesh(new THREE.CapsuleGeometry(.4,1.05,4,7),mats.zombie);m.position.y=1;m.castShadow=true;g.add(m);g.position.set(x,0,z);scene.add(g);zombies.push({obj:g,hp:35,speed:1.1+Math.random()*.55,state:'wander',dir:new THREE.Vector3(Math.random()-.5,0,Math.random()-.5).normalize(),attack:0})}
for(let i=0;i<12;i++){let a=Math.random()*Math.PI*2,d=25+Math.random()*65;spawnZombie(Math.cos(a)*d,Math.sin(a)*d)}
function dist2(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}
function nearestResource(){let best=null,bd=3.2;for(const r of resources)if(r.obj.visible){let d=dist2(player.position,r.obj.position);if(d<bd){best=r;bd=d}}return best}
function message(t){const el=document.querySelector('#message');el.textContent=t;el.classList.add('flash');clearTimeout(message.t);message.t=setTimeout(()=>el.classList.remove('flash'),1800)}
function harvest(){const r=nearestResource();if(!r){message('Nothing useful nearby');return}state[r.type]+=r.amount;r.obj.visible=false;r.respawn=30;state.noise=2;message('Collected '+r.amount+' '+r.type.toUpperCase())}
function eat(){if(state.food<1){message('No food');return}state.food--;state.hunger=Math.min(100,state.hunger+32);message('Ate food')}
function drink(){if(state.water<1){message('No water');return}state.water--;state.thirst=Math.min(100,state.thirst+38);message('Drank water')}
function craft(){const p=document.querySelector('#panel');p.innerHTML='<div class="panelTitle">CRAFTING</div><div class="hint">Use gathered materials to stay alive.</div><div class="row"><span>Water filter</span><button id="c1">2 SCRAP + 1 WOOD → 2 WATER</button></div><div class="row"><span>Rations</span><button id="c2">1 WOOD + 1 FOOD → 2 FOOD</button></div><div class="row"><span>Medkit</span><button id="c3">3 SCRAP + 1 FOOD → +35 HP</button></div><button id="close">CLOSE</button>';p.classList.remove('hidden');c1.onclick=()=>{if(state.scrap>=2&&state.wood>=1){state.scrap-=2;state.wood--;state.water+=2;message('Crafted water')}else message('Missing materials')};c2.onclick=()=>{if(state.wood>=1&&state.food>=1){state.wood--;state.food++;message('Cooked rations')}else message('Missing materials')};c3.onclick=()=>{if(state.scrap>=3&&state.food>=1){state.scrap-=3;state.food--;state.hp=Math.min(100,state.hp+35);message('Used medkit')}else message('Missing materials')};close.onclick=()=>p.classList.add('hidden')}
function inventory(){const p=document.querySelector('#panel');p.innerHTML='<div class="panelTitle">INVENTORY</div>'+[['WOOD',state.wood],['SCRAP',state.scrap],['STONE',state.stone],['FOOD',state.food],['WATER',state.water],['FUEL',Math.floor(state.fuel)]].map(x=>'<div class="row"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')+'<div class="hint">E interact/harvest · F eat · G drink · R drive · Space attack</div><button id="close">CLOSE</button>';p.classList.remove('hidden');close.onclick=()=>p.classList.add('hidden')}
function build(){buildMode=!buildMode;message(buildMode?'BUILD MODE: tap BUILD to place':'Build mode off')}
function placeBuild(){if(!buildMode)return;if(state.wood<4||state.scrap<2){message('Need 4 wood + 2 scrap');return}state.wood-=4;state.scrap-=2;const o=box(player.position.x,1,player.position.z-3,4,2,1,mats.wood);o.rotation.y=yaw;message('Barricade built')}
function toggleVehicle(){const d=dist2(player.position,car.position);if(!state.driving&&d>5){message('Move closer to the car');return}state.driving=!state.driving;message(state.driving?'DRIVING · R to exit':'On foot');if(state.driving)player.position.copy(car.position)}
function toggleCamera(){state.firstPerson=!state.firstPerson;message(state.firstPerson?'First person':'Third person')}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify({...state,x:player.position.x,z:player.position.z,yaw}));message('Game saved')}
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY));if(s){Object.assign(state,s);player.position.set(s.x||0,0,s.z||18);yaw=s.yaw||0;message('Save loaded')}}catch{}}
function attack(){let target=null,bd=3;for(const z of zombies){let d=dist2(player.position,z.obj.position);if(d<bd){target=z;bd=d}}if(target){target.hp-=25;state.noise=5;if(target.hp<=0){target.obj.visible=false;zombies.splice(zombies.indexOf(target),1);message('Zombie down')}else message('Hit')}else message('Swing')}
function moveInput(){let x=0,z=0;if(keys.KeyW||keys.ArrowUp)z-=1;if(keys.KeyS||keys.ArrowDown)z+=1;if(keys.KeyA||keys.ArrowLeft)x-=1;if(keys.KeyD||keys.ArrowRight)x+=1;x+=joystick.x;z+=joystick.y;const l=Math.hypot(x,z);return l>1?{x:x/l,z:z/l}:{x,z}}
function updatePlayer(dt){const inp=moveInput(),moving=Math.hypot(inp.x,inp.z)>.08;let speed=state.driving?9:3.7;if(keys.ShiftLeft&&state.stamina>1&&!state.driving){speed=6;state.stamina-=24*dt}else state.stamina=Math.min(100,state.stamina+12*dt);const f=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));const dir=f.clone().multiplyScalar(inp.z).add(r.multiplyScalar(inp.x));if(dir.lengthSq())dir.normalize();velocity.lerp(dir.multiplyScalar(speed),1-Math.pow(.001,dt));player.position.addScaledVector(velocity,dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-HALF+3,HALF-3);player.position.z=THREE.MathUtils.clamp(player.position.z,-HALF+3,HALF-3);if(moving)state.noise=Math.max(state.noise,state.driving?3:.3);if(state.driving){state.fuel=Math.max(0,state.fuel-dt*.7);if(state.fuel<=0)state.driving=false;car.position.lerp(player.position,.35);car.rotation.y=yaw}}
function updateZombies(dt){for(const z of zombies){if(!z.obj.visible)continue;const d=dist2(player.position,z.obj.position),heard=d<32&&state.noise>.5;z.state=(d<14||heard)?'chase':'wander';if(z.state==='chase'){const dx=player.position.x-z.obj.position.x,dz=player.position.z-z.obj.position.z,len=Math.hypot(dx,dz)||1;z.obj.position.x+=dx/len*z.speed*dt;z.obj.position.z+=dz/len*z.speed*dt;z.obj.rotation.y=Math.atan2(dx,dz);if(d<1.45){z.attack-=dt;if(z.attack<=0){state.hp-=7;z.attack=1;message('BITTEN')}}}else{z.obj.position.addScaledVector(z.dir,z.speed*.3*dt);if(Math.random()<.01)z.dir.set(Math.random()-.5,0,Math.random()-.5).normalize()}}}
function updateWorld(dt){state.time+=dt*.08;if(state.time>=24){state.time-=24;state.day++}state.hunger=Math.max(0,state.hunger-dt*.018);state.thirst=Math.max(0,state.thirst-dt*.027);state.noise=Math.max(0,state.noise-dt);if(state.hunger<10||state.thirst<10)state.hp-=dt*1.5;const a=state.time/24*Math.PI*2-Math.PI/2;sun.position.set(Math.cos(a)*80,Math.sin(a)*80,25);const daylight=Math.max(.08,Math.sin(a)*.55+.55);sun.intensity=daylight*2.2;hemi.intensity=.35+daylight;scene.background.setHSL(.58,.14,.18+.25*daylight);scene.fog.color.copy(scene.background);for(const r of resources)if(!r.obj.visible){r.respawn-=dt;if(r.respawn<=0)r.obj.visible=true}if(zombies.length<10+Math.floor(state.day/2)&&Math.random()<dt*.025){const a2=Math.random()*Math.PI*2,d=60+Math.random()*35;spawnZombie(player.position.x+Math.cos(a2)*d,player.position.z+Math.sin(a2)*d)}if(state.hp<=0&&!state.dead){state.dead=true;message('YOU DIED — refresh to restart')}}
function updateCamera(){if(state.firstPerson){camera.position.copy(player.position);camera.position.y+=1.55;camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch}else{const offset=new THREE.Vector3(0,2.8,6.5);offset.applyAxisAngle(new THREE.Vector3(0,1,0),yaw);camera.position.copy(player.position).add(offset);camera.lookAt(player.position.x,1.2,player.position.z)}}
function updateHUD(){for(const [id,v] of [['hp',state.hp],['hunger',state.hunger],['thirst',state.thirst],['stamina',state.stamina]])document.querySelector('#'+id).style.width=Math.max(0,v)+'%';document.querySelector('#stats').textContent='WOOD '+state.wood+' · SCRAP '+state.scrap+' · STONE '+state.stone+' · FOOD '+state.food+' · WATER '+state.water;const h=String(Math.floor(state.time)).padStart(2,'0'),m=String(Math.floor(state.time%1*60)).padStart(2,'0');document.querySelector('#clock').textContent='DAY '+state.day+' · '+h+':'+m+(state.driving?' · DRIVING':'')}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')harvest();if(e.code==='KeyF')eat();if(e.code==='KeyG')drink();if(e.code==='KeyR')toggleVehicle();if(e.code==='Space')attack();if(e.code==='KeyC')toggleCamera();if(e.code==='KeyB')build();if(e.code==='KeyL')save()});addEventListener('keyup',e=>keys[e.code]=false);
document.querySelector('#inventory').onclick=inventory;document.querySelector('#craft').onclick=craft;document.querySelector('#build').onclick=()=>buildMode?placeBuild():build();document.querySelector('#vehicle').onclick=toggleVehicle;document.querySelector('#camera').onclick=toggleCamera;document.querySelector('#save').onclick=save;
let joyPointer=null;const joy=document.querySelector('#joystick'),stick=document.querySelector('#stick');joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId)});joy.addEventListener('pointermove',e=>{if(e.pointerId!==joyPointer)return;const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),l=Math.min(43,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);joystick.x=Math.cos(a)*l/43;joystick.y=Math.sin(a)*l/43;stick.style.transform='translate('+joystick.x*43+'px,'+joystick.y*43+'px)'});joy.addEventListener('pointerup',()=>{joyPointer=null;joystick.x=joystick.y=0;stick.style.transform=''});
let lastX=0,lastY=0;document.querySelector('#lookpad').addEventListener('pointerdown',e=>{look.active=true;lastX=e.clientX;lastY=e.clientY});document.querySelector('#lookpad').addEventListener('pointermove',e=>{if(!look.active)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;yaw-=dx*.008;pitch=THREE.MathUtils.clamp(pitch-dy*.006,-1.35,1.2)});addEventListener('pointerup',()=>look.active=false);
renderer.domElement.addEventListener('click',()=>{if(buildMode)placeBuild();else attack()});
load();let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!state.dead){updatePlayer(dt);updateZombies(dt);updateWorld(dt)}updateCamera();updateHUD();renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
